import Link from "next/link";
import { ArrowUpRight, BookOpen, Brain, Clock3, FileText, Flame, Mic2, Play, Sparkles, Target, Trophy } from "lucide-react";
import { Badge, IconTile, ProgressBar } from "./ui";

const activities = [
  { icon: Trophy, title: "Completed a quiz", detail: "Newton's Laws · 12 min ago", score: "82%", tone: "bg-emerald-50 text-emerald-600" },
  { icon: BookOpen, title: "Studied a new topic", detail: "Kinematics · Yesterday", score: "25 min", tone: "bg-blue-50 text-blue-600" },
  { icon: Brain, title: "Learning Twin updated", detail: "Confidence profile · Yesterday", score: "New", tone: "bg-violet-50 text-violet-600" },
];

export function Dashboard() {
  return <div className="mx-auto max-w-[1440px]">
    <section className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary" /> Monday, September 7, 2026</div><h1 className="font-display text-4xl font-bold tracking-tight text-ink sm:text-5xl">Good evening, Alex <span className="text-3xl">👋</span></h1><p className="mt-3 text-sm text-slate-500">Let&apos;s continue building your knowledge.</p></div><div className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-500 shadow-sm"><Flame size={15} className="text-orange-500" /> 7 day streak</div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Brain} label="Learning Twin" value="74%" detail="Confidence score" tone="bg-indigo-50 text-primary" /><Metric icon={Target} label="Quiz performance" value="82%" detail="+8% this month" tone="bg-violet-50 text-accent" /><Metric icon={Flame} label="Learning streak" value="7 days" detail="Best: 12 days" tone="bg-orange-50 text-orange-600" /><Metric icon={Clock3} label="Learning time" value="4.5h" detail="This week" tone="bg-sky-50 text-sky-600" /></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_1fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-6 flex items-center justify-between"><div><div className="mb-1 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-primary"><Sparkles size={14} /> Personalized snapshot</div><h2 className="font-display text-xl font-bold text-ink">Your Learning Twin</h2></div><Link className="flex items-center gap-1 text-xs font-bold text-primary hover:text-accent" href="/learning-twin">View profile <ArrowUpRight size={14} /></Link></div><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="relative grid h-32 w-32 shrink-0 place-items-center rounded-full bg-[conic-gradient(#4f46e5_0_74%,#eef2ff_74%_100%)]"><div className="grid h-24 w-24 place-items-center rounded-full bg-white"><span className="font-display text-3xl font-bold text-ink">74<small className="block text-center font-sans text-[9px] font-semibold uppercase tracking-wider text-slate-400">confidence</small></span></div></div><div><h3 className="font-display text-lg font-bold text-ink">You&apos;re building momentum.</h3><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Your twin sees that you learn best with visual examples and step-by-step explanations.</p><div className="mt-4 flex flex-wrap gap-2"><Badge>Visual learner</Badge><Badge tone="violet">Step-by-step</Badge><Badge tone="emerald">Curious</Badge></div></div></div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-6 flex items-center justify-between"><h2 className="font-display text-xl font-bold text-ink">Recent activity</h2><Link className="text-xs font-bold text-primary hover:text-accent" href="/progress">See all</Link></div><div className="space-y-5">{activities.map(({ icon: Icon, title, detail, score, tone }) => <div className="flex items-center gap-3" key={title}><IconTile icon={Icon} className={tone} /><div className="min-w-0 flex-1"><strong className="block truncate text-xs font-semibold text-ink">{title}</strong><span className="mt-1 block text-[11px] text-slate-400">{detail}</span></div><span className="text-xs font-bold text-primary">{score}</span></div>)}</div></article></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[1fr_1fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between"><div><div className="mb-1 text-xs font-bold uppercase tracking-wider text-primary">Keep the momentum</div><h2 className="font-display text-xl font-bold text-ink">Continue learning</h2></div><BookOpen className="text-slate-300" size={21} /></div><div className="rounded-xl border border-indigo-100 bg-indigo-50/60 p-4"><div className="flex items-center justify-between"><div><Badge>In progress</Badge><h3 className="mt-3 font-semibold text-ink">Algebra foundations</h3><p className="mt-1 text-xs text-slate-500">Practice equations with guided examples.</p></div><span className="font-display text-2xl font-bold text-primary">62%</span></div><ProgressBar value={62} /><div className="mt-2 flex justify-between text-[10px] font-medium text-slate-400"><span>3 lessons remaining</span><span>Last studied today</span></div></div></article><article className="relative overflow-hidden rounded-2xl bg-ink p-5 text-white shadow-soft sm:p-6"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full border border-indigo-400/20" /><div className="relative"><div className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-300"><Sparkles size={14} /> Quick actions</div><h2 className="font-display text-xl font-bold">What would you like to do?</h2><div className="mt-5 grid grid-cols-2 gap-2"><QuickAction href="/ask" icon={Brain} label="Ask AI" /><QuickAction href="/upload" icon={FileText} label="Upload PDF" /><QuickAction href="/quiz" icon={Play} label="Take quiz" /><QuickAction href="/lecture" icon={Mic2} label="Record lecture" /></div></div></article></section>
  </div>;
}

function Metric({ icon: Icon, label, value, detail, tone }: { icon: typeof Brain; label: string; value: string; detail: string; tone: string }) { return <article className="group rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-1 hover:shadow-soft"><div className="flex items-start justify-between"><IconTile icon={Icon} className={tone} /><ArrowUpRight size={16} className="text-slate-300 transition group-hover:text-primary" /></div><p className="mt-5 text-xs font-semibold text-slate-500">{label}</p><div className="mt-1 flex items-end justify-between"><strong className="font-display text-2xl font-bold text-ink">{value}</strong><span className="text-[10px] font-medium text-slate-400">{detail}</span></div></article>; }
function QuickAction({ href, icon: Icon, label }: { href: string; icon: typeof Brain; label: string }) { return <Link href={href} className="flex items-center gap-2.5 rounded-xl border border-white/10 bg-white/10 p-3 text-xs font-semibold text-slate-200 transition hover:bg-white/20"><Icon size={16} className="text-indigo-300" />{label}</Link>; }
